[cleanup] Follow-ups from initial mypy PR
Summary:
A couple follow-ups from #22:
- Add TODO for type checking FLAVA code
- Add a couple other type hints missed by mypy in clip_text_encoder (due to https://mypy.readthedocs.io/en/stable/common_issues.html#no-errors-reported-for-obviously-wrong-code)
- Some changes to weighted_embedding_encoder to silence mypy errors

Test plan:
```
$ python -m pytest -v
...
====================================================================================== short test summary info =======================================================================================
FAILED test/transforms/test_clip_transform.py::TestCLIPTransform::test_clip_multi_transform - requests.exceptions.MissingSchema: Invalid URL '/data/home/ebs/torchmultimodal/torchmultimodal/test/a...
FAILED test/transforms/test_clip_transform.py::TestCLIPTransform::test_clip_single_transform - requests.exceptions.MissingSchema: Invalid URL '/data/home/ebs/torchmultimodal/torchmultimodal/test/...
================================================================== 2 failed, 48 passed, 3 skipped, 26 warnings in 76.48s (0:01:16) ===================================================================

```
(Failures are pre-existing and will be fixed with a separate commit)

```
$ mypy
Success: no issues found in 29 source files
```

[ghstack-poisoned]