Fix warnings thrown during testing: FLAVA, SamePadConv (#325)
Summary:
Pull Request resolved: https://github.com/facebookresearch/multimodal/pull/325

Fixed the following warnings:

```
test/models/flava/test_checkpoint.py::TestFLAVACheckpoint::test_flava_model_for_pretraining
  /data/home/langong/repos/ci/test/models/flava/test_checkpoint.py:105: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
    else torch.tensor(dict_actual[key])

test/modules/layers/test_conv.py::TestSamePadConv3d::test_samepadconv3d_forward
  /data/home/langong/repos/ci/torchmultimodal/modules/layers/conv.py:49: UserWarning: Padding was specified but will not be used in favor of same padding,                 use Conv3d directly for custom padding
    warnings.warn(
```

Add ignore to `pooling_function` of `mil_encoder.py` to suppress `mypy` error:

```
torchmultimodal/modules/encoders/mil_encoder.py:73:30: error: Argument
Installing missing stub packages:
/usr/share/miniconda3/envs/test/bin/python -m pip install types-setuptools types-tabulate

Found 1 error in 1 file (checked 59 source files)
"pooling_function" has incompatible type "Callable[..., Any]"; expected
"TransformerEncoder"  [arg-type]
                pooling_function=pooling_function,
                                 ^~~~~~~~~~~~~~~~
```

Test Plan:
- `python -m pytest test/modules/layers/test_conv.py`
- `python -m pytest test/models/flava/test_checkpoint.py`

Reviewed By: pikapecan

Differential Revision: D39833572

Pulled By: langong347

fbshipit-source-id: 8e1647d65f25885e141541b4d2ef755f269a1fcc